/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      "colors": {
          "primary-container": "#1cb853",
          "surface-tint": "#72fe8f",
          "on-error": "#450900",
          "on-primary": "#005f26",
          "surface": "#0e0e0e",
          "on-surface": "#ffffff",
          "outline-variant": "#484847",
          "inverse-on-surface": "#565555",
          "on-secondary": "#005e39",
          "on-primary-container": "#002a0c",
          "secondary-fixed-dim": "#6deca8",
          "secondary": "#7cfbb5",
          "primary-fixed-dim": "#63ef82",
          "error": "#ff7351",
          "secondary-container": "#006d42",
          "on-secondary-fixed": "#00492b",
          "background": "#0e0e0e",
          "on-background": "#ffffff",
          "on-tertiary-fixed": "#003840",
          "surface-container": "#1a1a1a",
          "on-primary-fixed": "#004a1c",
          "on-tertiary-fixed-variant": "#005763",
          "primary-fixed": "#72fe8f",
          "on-error-container": "#ffd2c8",
          "primary": "#72fe8f",
          "on-tertiary-container": "#004d58",
          "on-surface-variant": "#adaaaa",
          "inverse-primary": "#006e2d",
          "secondary-fixed": "#7cfbb5",
          "surface-variant": "#262626",
          "inverse-surface": "#fcf9f8",
          "surface-bright": "#2c2c2c",
          "on-tertiary": "#005762",
          "tertiary-container": "#0fe3ff",
          "primary-dim": "#63ef82",
          "surface-container-high": "#20201f",
          "tertiary": "#88ebff",
          "tertiary-fixed": "#0fe3ff",
          "tertiary-dim": "#00d4ee",
          "error-container": "#b92902",
          "on-secondary-container": "#e2ffe9",
          "surface-container-low": "#131313",
          "surface-container-highest": "#262626",
          "outline": "#767575",
          "error-dim": "#d53d18",
          "tertiary-fixed-dim": "#00d4ee",
          "surface-container-lowest": "#000000",
          "secondary-dim": "#6deca8",
          "on-primary-fixed-variant": "#006a2b",
          "surface-dim": "#0e0e0e",
          "on-secondary-fixed-variant": "#006940"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "2xl": "1rem",
          "3xl": "1.5rem",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Plus Jakarta Sans"],
          "body": ["Inter"],
          "label": ["Inter"]
      }
    }
  },
  plugins: [],
}
